# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WILLNODE
email: wildanmubarok22@gmail.com
author: Wildan Mubarok
description: >-
  The place for hand-crafted stories and facts from my own personal experience.
descriptionid: >-
  Tempatnya bercerita dan berfakta dari tangan pengalaman saya sendiri.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://wellosoft.net" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:title.html

sass:
  style: compressed
# Build settings
markdown: kramdown
#plugins:
#  - jekyll-feed
#  - jekyll-gist

google_analytics: "UA-109180894-1"

disqus:
  shortname: willnode

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "drafts"
    values:
      layout: "post"
      hidden: true
  -
    scope:
      path: "id"
    values:
      lang: "id"
  -
    scope:
      path: "en"
    values:
      lang: "en"